version: '3'

services:
  squid:
    build:
      context: ./
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./conf/whitelist_dstdomain.conf:/etc/squid/whitelist_dstdomain.conf
      - ./conf/whitelist_url_regex.conf:/etc/squid/whitelist_url_regex.conf
      - ./log/:/var/log/squid
    ports:
      - "${SQUID_BIND_IP_PORT:-127.0.0.1:3128}:3128"
    restart: always
